channels:
- conda-forge
dependencies:
- python=3.9.13
- pip<=23.2.1
- pip:
  - mlflow==3.1.4
  - cloudpickle==3.1.1
  - numpy==2.0.2
  - pandas==2.3.1
  - psutil==7.0.0
  - scikit-learn==1.6.1
  - scipy==1.13.1
name: mlflow-env
