name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    # If you don’t need the DVC container service, you can delete this entire block.
    # Keep it only if you have a very custom DVC setup.
    #services:
    #  dvc-cache:
    #    image: docker.io/iterativeai/dvc:2
    #    options: --entrypoint tail
    #    # (Removed the invalid `command:` key)

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install dvc[all] pytest flask mlflow

      - name: Pull data & run pipeline
        run: |
          source .venv/bin/activate
          dvc pull --quiet
          dvc repro --force

      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest --maxfail=1 --disable-warnings -q

      - name: Build Docker image
        run: |
          docker build -t sentiment-api:${{ github.sha }} .

      # Optional: Push to Docker Hub (requires registry secrets)
      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      #
      # - name: Push Docker image
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: .
      #     push: true
      #     tags: yourdockerhubuser/sentiment-api:latest

      - name: Archive model image tag
        run: |
          echo "Image built: sentiment-api:${{ github.sha }}"
