name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install "dvc[all]" pytest flask mlflow

      - name: Configure DVC AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          dvc remote modify --local storage access_key_id     "$AWS_ACCESS_KEY_ID"
          dvc remote modify --local storage secret_access_key "$AWS_SECRET_ACCESS_KEY"

      - name: Pull data & run pipeline
        # Ensure MLflow writes into the workspace, not under /Users
        env:
          MLFLOW_TRACKING_URI: ${{ github.workspace }}/mlruns
        run: |
          dvc pull --quiet
          dvc repro --force

      - name: Run tests
        env:
          MLFLOW_TRACKING_URI: ${{ github.workspace }}/mlruns
        run: |
          pytest --maxfail=1 --disable-warnings -q

      - name: Build Docker image
        run: |
          docker build -t sentiment-api:${{ github.sha }} .

      - name: Archive model image tag
        run: |
          echo "Image built: sentiment-api:${{ github.sha }}"
