# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      # point MLflow at the mlruns/ folder in your repo root
      MLFLOW_TRACKING_URI: file://${{ github.workspace }}/mlruns

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install "dvc[all]" pytest flask mlflow

      - name: Configure DVC AWS credentials
        run: |
          dvc remote modify --local storage access_key_id     ${{ secrets.AWS_ACCESS_KEY_ID }}
          dvc remote modify --local storage secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Pull data & run pipeline
        run: |
          dvc pull --quiet
          dvc repro --force

      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings -q

      - name: Build Docker image
        run: docker build -t sentiment-api:${{ github.sha }} .

      - name: Archive model image tag
        run: |
          echo "Image built: sentiment-api:${{ github.sha }}"
