name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    # Pass AWS creds/region to all steps (DVC/boto3 will read these)
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Install the S3 extra for DVC; lighter and sufficient
          pip install "dvc[s3]" pytest flask mlflow

      # Optional sanity; helps surface config in logs
      - name: DVC diagnostics
        run: |
          python -V
          dvc --version
          dvc remote list
          echo "--- .dvc/config ---"
          cat .dvc/config || true

      - name: Pull data & run pipeline (verbose)
        run: |
          set -euxo pipefail
          dvc pull -v
          dvc repro -v --force

      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q

      - name: Build Docker image
        run: |
          docker build -t sentiment-api:${{ github.sha }} .

      - name: Archive model image tag
        run: |
          echo "Image built: sentiment-api:${{ github.sha }}"
